FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build-env
WORKDIR /dotnet-api

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine
WORKDIR /app
COPY --from=build-env /dotnet-api/out .

ENTRYPOINT ["dotnet", "dotnet-api.dll"]